#!/bin/bash

echo "Install Nix"
sh <(curl -L https://nixos.org/nix/install)

echo "Install Homebrew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

echo "Creating nix config folder"
mkdir -p ~/.config/nix

echo "Getting darwin flake"
cd ~/.config/nix
curl -L thalesgelinger.com/sh/flake.nix -o flake.nix

echo "Run nix setup"
nix run nix-darwin --extra-experimental-features "nix-command flakes" -- switch --flake ~/.config/nix#thales

echo "Setup dotifles"
cd ~
git clone https://github.com/thalesgelinger/.dotfiles.git
cd .dotfiles
stow .


echo "Add asdf plugins"
asdf plugin add golang https://github.com/asdf-community/asdf-golang.git
asdf install golang latest
asdf global golang latest

asdf plugin add erlang https://github.com/asdf-vm/asdf-erlang.git
asdf install erlang latest
asdf global erlang latest

asdf plugin add nodejs
asdf install nodejs latest
asdf global nodejs latest

asdf plugin add rust
asdf install rust latest
asdf global rust latest

asdf plugin add bun
asdf install bun latest
asdf global bun latest

asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
asdf install elixir latest
asdf global elixir latest

echo "Add Project dir"
mkdir ~/Projects

echo "Clone wallpapers"
cd ~
git clone https://github.com/thalesgelinger/wallpapers.git

echo "Finishing setup"
