#!/bin/bash


function brew_stuff() {
    echo "Install Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    brew_packages=(
      fish
      git
      stow
      aerospace                       
      bruno                           
      discord                         
      figma                           
      zen-browser
      firefox                         
      font-hack-nerd-font             
      font-jetbrains-mono-nerd-font   
      font-monaspace-nerd-font        
      font-noto-sans-symbols-2        
      love                            
      microsoft-teams                 
      minisim
      raycast
      slack
      wezterm
      asdf-vm
      slack
      neovim
      ripgrep
      tldr
      tmux
      ollama
      ffmpeg
    )

    for package in "${brew_packages[@]}"
    do
      echo "Installing $package..."
      brew install "$package"
    done
}

brew_stuff

echo "Setup fish"
sudo sh -c 'echo /usr/local/bin/fish >> /etc/shells'
chsh -s /usr/local/bin/fish

echo "Setup dotifles"
cd ~
git clone https://github.com/thalesgelinger/.dotfiles.git
cd .dotfiles
stow .


echo "Add asdf plugins"
asdf plugin add golang https://github.com/asdf-community/asdf-golang.git
asdf install golang latest
asdf global golang latest

asdf plugin add erlang https://github.com/asdf-vm/asdf-erlang.git
asdf install erlang latest
asdf global erlang latest

asdf plugin add nodejs
asdf install nodejs latest
asdf global nodejs latest

asdf plugin add rust
asdf install rust latest
asdf global rust latest

asdf plugin add bun
asdf install bun latest
asdf global bun latest

asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
asdf install elixir latest
asdf global elixir latest

echo "Add Project dir"
mkdir ~/Projects
mkdir ~/Projects/personal/
mkdir ~/Projects/work/

echo "Clone wallpapers"
cd ~
git clone https://github.com/thalesgelinger/wallpapers.git

function mac_defaults(){
    echo "Setting up macos defaults"
    # Dock settings
    defaults write com.apple.dock autohide -bool true  # Enable dock autohide
    defaults write com.apple.dock tilesize -int 16  # Set dock tile size to 16
    defaults write com.apple.dock orientation -string "right"  # Set dock to right
    killall Dock  # Restart Dock to apply changes

    # Global Menu Bar
    defaults write NSGlobalDomain _HIHideMenuBar -bool true  # Hide the menu bar by default

    # Finder settings
    defaults write com.apple.finder ShowStatusBar -bool true  # Show the status bar in Finder
    defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"  # Set Finder search scope to "This Mac"
    defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"  # Set Finder view to List View
    defaults write com.apple.finder CreateDesktop -bool false  # Disable desktop icons
    killall Finder  # Restart Finder to apply changes

    # defaults write com.apple.desktop Background '{default = {ImageFilePath = "~/wallpapers"; };}'
}

mac_defaults

echo "Finishing setup"

exit
