#!/bin/bash

echo "Install Nix"
sh <(curl -L https://nixos.org/nix/install)

echo "Install Homebrew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

echo "Creating nix config folder"
mkdir -p ~/.config/nix

echo "Getting darwin flake"
cd ~/.config/nix
curl -L thalesgelinger.com/sh/flake.nix -o flake.nix

echo "Run nix setup"
nix run nix-darwin --extra-experimental-features "nix-command flakes" -- switch --flake ~/.config/nix#thales

echo "Setup dotifles"
cd ~
git clone https://github.com/thalesgelinger/.dotfiles.git
cd .dotfiles
stow .

echo "Finishing setup"
